spring:
  datasource:
    username: dbeventlog
    password: dbeventlog
    url: jdbc:mariadb://localhost:3307/eventlog
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate

